\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{asabina}[2018/10/08 A Corporate LaTeX Class]
% This class uses the scrartcl class
\LoadClass[%
  a4paper,
  10pt,
  version=last
]{scrartcl}
% Configure Layout dimensions
\RequirePackage[
  reset,
  bottom=3.2cm,
  headheight=1cm,
  left=2cm,
  right=2cm,
  top=2cm,
  nofoot
]{geometry}
% Language
\RequirePackage[english,german]{babel}
% Disables indentation
\setlength{\parindent}{0cm}
% Set the font
\RequirePackage{fontspec}
\setmainfont[Ligatures=TeX, Scale=0.8]{Montserrat-Regular}
% Set the main font (Montserrat) to section headings and toc
\addtokomafont{disposition}{\rmfamily}
\RequirePackage{etoolbox}
\RequirePackage{numprint}
\RequirePackage[table]{xcolor}
\RequirePackage{atbegshi} % Provides command to place TikZ footer on every page
\RequirePackage{array}
\RequirePackage{xparse}  % To define commands and environments
\RequirePackage{xstring} % To test when the pagenumbers are well defined

\widowpenalty10000	% Is infinitely bad to have widow lines
\clubpenalty100000	% Is infinitely bad to have orphan lines

\RequirePackage[hidelinks]{hyperref}
\RequirePackage[atend]{bookmark}

\RequirePackage{tikz}
\usetikzlibrary{calc}

\newcommand\Footer{
\begin{tikzpicture}[remember picture, overlay]
\node(background) [
  shape=rectangle,
  fill=black,
  minimum width=\paperwidth,
  minimum height=2.5cm,
  text width=0.92\paperwidth,
  text height=-0.2cm,
  anchor=south west,
  font=\footnotesize\bfseries, align=left
] at (current page.south west){\color{white}
  \begin{minipage}[t]{0.215\textwidth}\baselineskip=10pt
    \tiny
    \AgreementSupplierName\\
    \AgreementSupplierAddress\\
    \AgreementSupplierPostalcode\ \AgreementSupplierPlace\\
    \LabelManagement: \AgreementSupplierManager\\
  \end{minipage}
  \begin{minipage}[t]{0.315\textwidth}\baselineskip=10pt
    \tiny
    \LabelChamberOfCommerce: \AgreementSupplierRegister\\
    \LabelCourt: \AgreementSupplierRegistryCourt\\
    \LabelTaxId: \AgreementSupplierTaxNumber\\
    \LabelVatId: \AgreementSupplierVATCode\\
  \end{minipage}
  \begin{minipage}[t]{0.22\textwidth}\baselineskip=10pt
    \tiny
    \LabelBankDetails: \AgreementSupplierBankInhaber\\
    \LabelBIC: \AgreementSupplierBankBIC\\
    \LabelIBAN: \AgreementSupplierBankIBAN
  \end{minipage}
};
\ifdef{\AgreementSupplierFooterLogo}{
  \node[anchor=south east, yshift=0.2cm] at (current page.south east) {\AgreementSupplierFooterLogo};
}{}
\end{tikzpicture}}

\AtBeginShipout{\AtBeginShipoutAddToBox{\Footer}}

% Caption of figures
  \renewcommand{\thefigure}{\arabic{section}.\arabic{figure}}
  \addto\captionsgerman{
  \renewcommand{\figurename}{Fig.}
  }





